In [1]:
# NUMPY

# Numpy is a python library for performing mathematical operations.
# Since we have learnt python pandas relys on numpy

In [ ]:
# In this notebook we will be looking at:
# Creating one dimensional arrays(HAVING ONLY ONE ROW)
# The basic data-types of arrays in numpy
# Indexing ans slicing of one dimensional arrays(HAVE ONLY ONE ROW)

In [3]:
import numpy as np

In [4]:
# We create an array of integers
# Arrays should have the same data-type

integers_array = np.array([1 , 2,3,4,5,6,7])
integers_array

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# We check the datatype of the array we just cdreated. Should be int64

integers_array.dtype

dtype('int64')

In [6]:
# Create a another array of floats

floats_array = np.array([.5 , .4 ,.6 , .7])
floats_array

array([0.5, 0.4, 0.6, 0.7])

In [ ]:
# Check the dataype of the array we created should be float64
 
floats_array.dtype

dtype('float64')

In [10]:
# When creating an array despite them bing integers you may want to change the datatype of the array

change_dtype_array = np.array([3,4,5,6,7,8] , dtype= 'float64')
change_dtype_array

array([3., 4., 5., 6., 7., 8.])

In [ ]:
# We may want to change the data-type again
change_dtype_array.astype('int64')

array([3, 4, 5, 6, 7, 8])

In [20]:
# We create another array of strings

strings_array = np.array(['A' , 'B' , 'C' , 'D'])
strings_array

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [23]:
# What about a dictionary

dictionary_array = np.array({'A' : 'Pass'})
dictionary_array

array({'A': 'Pass'}, dtype=object)

In [24]:
print(f"Array1 = {floats_array.dtype} \nArray2 ={integers_array.dtype} \nArray3 = {strings_array.dtype} \nArray4 = {dictionary_array.dtype}")

Array1 = float64 
Array2 =int64 
Array3 = <U1 
Array4 = object


In [25]:
# Also we can slice and index arrays just like in python

# Selectts the 1st element in the array
integers_array[0]

np.int64(1)

In [26]:
# Selecting the 1st element in the floats

floats_array[0]

np.float64(0.5)

In [27]:
# We can also slice

floats_array[0 : 2]

array([0.5, 0.4])

In [28]:
# numpy also supports multi nindexing
# Like we can selcet multiple indexes at once

# Lets say we select elements at the 1st , 3rd and last index

floats_array[[ 0 , 2 , -1]]

array([0.5, 0.6, 0.7])