In [1]:
# Apart from the normal mathematical operations that we have other opearations we can perform THE BOOLEAN OPERATIONS.

# BOOLEAN OPERATIONS = > , < , >= 

In [2]:
import numpy as np

In [4]:
# We create an array 

b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [5]:
# Lets say we want to select items in the 1st index and last index

# We use multi-indexing what we learnt in the last lesson

b[[0 , -1]]

array([0, 4])

In [7]:
# We can also select the indexing using boolean expressions

# The indexes we want to select we pass true the ones we want to drop we pass false

b[[True , False , False , False , True]]

array([0, 4])

In [ ]:
# This returns True for those which are greater than 2 and False for those less than 2
b > 2

array([False, False, False,  True,  True])

In [ ]:
# If we dont want it to return true or false but the values rather we filter further

# This means for array b , select values that are greater than 2
b[b > 2]

array([3, 4])

In [10]:
# mean of every value in the array

b.mean()

np.float64(2.0)

In [11]:
# We display the values which are greater than the mean
b[b > b.mean() ]

array([3, 4])

In [25]:
# We can also combine more than one boolean expression

# we display values which are equal to 0 or equal to two

# we know we should expect to see 0 and 2

c = np.array([0 , 1, 2 ,3 ,4])

c[(c == 0) | (c == 2)]



array([0, 2])

In [29]:
np.random.randint(100 , size= (3 , 3))

array([[11, 38, 85],
       [65, 74, 79],
       [38,  5, 17]], dtype=int32)