In [1]:
# This notebook we will look at Broadcasting and vectorised Operations



In [2]:
import numpy as np


In [6]:
# We generate an array with upto 4 elemements
a = np.arange(4)
a

array([0, 1, 2, 3])

In [7]:
# We can add each value in the array by a certain value

a + 10

array([10, 11, 12, 13])

In [8]:
# We can perform other operations such as multipilication
a * 2

array([0, 2, 4, 6])

In [12]:
a += 100
a

array([300, 301, 302, 303])

In [16]:
# We can also use a loop to perform this operations

b = np.array([1 ,2, 3, 4])
b =[i + 4 for i in b]
b


[np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

In [19]:
# We can also perform multiple operations on multiple arrays together depending on what we want to achieve

# We can add , multiply , divide an array with each ONLY IF THEY ARE OF THE SAME SIZE

array_1 = np.array([1 , 2 , 3])
array_2 = np.array([4 , 5 , 6 ])

array_1 + array_2



array([5, 7, 9])