In [1]:
# Other numpy functions that could be of use


In [2]:
import numpy as np

In [ ]:
# RANDOM
# 1st argument is the range like any number from 0 to 10
# 2nd parameter size is the number of elements
np.random.randint( 10 , size= 20)

array([9, 0, 6, 8, 3, 7, 6, 8, 1, 7, 1, 8, 0, 6, 1, 3, 0, 8, 5, 4],
      dtype=int32)

In [22]:
np.random.rand(2  , 4)


array([[0.69224209, 0.10812574, 0.65054701, 0.81170681],
       [0.4576225 , 0.9405784 , 0.11596884, 0.87987255]])

In [21]:
np.random.normal(size = 2)

array([-1.05775019, -0.27997337])

In [23]:
# RESHAPE

np.arange(10).reshape(2 , 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# linspace

np.linspace(0 , 1 , 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# Zeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((3 , 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# ones

np.ones(4)

array([1., 1., 1., 1.])

In [28]:
np.ones((3 , 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Identity = equal rows and columns. 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# eye

# Returns a 2 dimensional array with ones on the diagonal and zeros elsewhere
np.eye(3 , 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(8 , 4 ,  k= 1)
# k :
# Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.eye(8 , 4 , k = -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])