In [1]:
# This notebook focuses on Linear Algebra

In [2]:
# We create a multi dimenasional array specifically a cube

In [3]:
import numpy as np

In [4]:
A = np.array([
    [0 , 1 ,2] ,
    [3 , 4 ,5] ,
    [6 , 7 ,8]
])

In [7]:
# We create a second multi dimesional array but this one with 2 columns but 3 rows

B = np.array([
    [2 ,3] ,
    [4 , 5] ,
    [6 , 7]
])

In [6]:
A.shape

(3, 3)

In [8]:
B.shape

(3, 2)

In [9]:
A.dot(B)

array([[ 16,  19],
       [ 52,  64],
       [ 88, 109]])

In [10]:
A @ B

array([[ 16,  19],
       [ 52,  64],
       [ 88, 109]])

In [11]:
B.T

array([[2, 4, 6],
       [3, 5, 7]])