In [ ]:
# In this notebook we will be looking at :
# multideminsional arrays(having more than one row)
# The opeartions we use to manipulate multidimesional arrays
# Indexing and slicing multi-dimensional array

In [2]:
import numpy as np

In [6]:
# We create an array with 2 rows and several columns

multi_array = np.array([
    [1 , 2 , 3] , 
    [6 ,7 ,8] ,
])
multi_array

array([[1, 2, 3],
       [6, 7, 8]])

In [10]:
# we can check the:
# shape - number of rows and columns
# size - number of elemnents in our array

print(f"Shape = {multi_array.shape} \nSize = {multi_array.size} \nData_Type = {multi_array.dtype} ")

Shape = (2, 3) 
Size = 6 
Data_Type = int64 


In [ ]:
# We can also index and slice multi dimessiona arrays

# syntax is rows 1st then columns



In [ ]:
# eg

# select 1st row only. SHOULD DISPLAY 1 , 2 ,3
multi_array[0]

array([1, 2, 3])

In [ ]:
# Select the second row . SHOULD DISPLAY 6 , 7 ,8

multi_array[1]

array([6, 7, 8])

In [13]:
# Now what if I wanted to select both the row and the columns

# Select the 1st row and 1st column

multi_array[0 , 0]

np.int64(1)

In [ ]:
# 1st row and elements from 1 upto last index

multi_array[0 , 1:]

array([2, 3])