In [1]:
# This notebook will be more driven towards the exercises of the functions of numpy

In [2]:
import numpy as np

In [4]:
# Create a numpy array of size 10 filled with zeros

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Create a numpy array with values ranging from 10 to 49

b = np.arange(10 , 59)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

In [10]:
# Create a numpy matrix of 2 * 2 integers filled with ones

a_ones = np.ones( [2 , 2] , dtype= 'int64')
a_ones

array([[1, 1],
       [1, 1]])

In [15]:
# Create a numpy matrix of 3 * 2 float numbers , filled with ones

# b_ones = np.ones([3 , 2] , dtype = np.float64) 
b_ones = np.ones([3 , 2] , dtype= 'float')
b_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Given the X numpy array , create a numpy array with the same shape and type as X , filled with ones

x_ones = np.arange(4)

np.ones_like(x_ones)

print(f"X Array = {x_ones} \nOne Array = {np.ones_like(x_ones)}")

X Array = [0 1 2 3] 
One Array = [1 1 1 1]


In [26]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

x_matrix = np.array([[2 , 3 , 4] , [5 , 6 ,7]])
np.zeros_like(x_matrix)

print(f"X Array = {x_matrix} \nOne Array = {np.zeros_like(x_matrix)}")

X Array = [[2 3 4]
 [5 6 7]] 
One Array = [[0 0 0]
 [0 0 0]]


In [28]:
# Create a numpy matrix of 4*4 integers, filled with fives.

five_array = np.ones([4 , 4]  , dtype= 'int64') *5
five_array

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [34]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

seven_array = np.array([[5 , 5] , [ 3 , 4]])

np.ones_like(seven_array) * 7

print(f"Array = {seven_array} \nSeven_Array = {np.ones_like(seven_array) * 7}")

Array = [[5 5]
 [3 4]] 
Seven_Array = [[7 7]
 [7 7]]


In [39]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

identity_matrix = np.identity(3)
identity_matrix

similar_identity = np.eye(3)
similar_identity

print(f"Identity Matrix = {identity_matrix} \nSimlar Matrix = {similar_identity}")

Identity Matrix = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
Simlar Matrix = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.

random_array = np.random.randint(10 , size = 3)
random_array

array([6, 3, 3], dtype=int32)

In [43]:
# Create a 3*3*3 numpy matrix, filled with random float values.

three_array = np.random.randn(3 , 3 , 3)
three_array

array([[[-0.58753537,  1.30239608,  1.64410744],
        [ 2.7181583 ,  0.71059852,  1.61325257],
        [-1.46303488,  0.0882945 , -1.89502577]],

       [[ 0.31580439, -0.33089864, -1.77174285],
        [ 0.08827466,  0.02967195,  1.1660144 ],
        [ 1.06664575, -0.4336059 , -1.0639087 ]],

       [[ 1.3929858 ,  0.5759542 , -1.05755154],
        [-0.97384273, -0.60058059, -0.64666646],
        [-0.45623179, -0.65108183, -1.5037608 ]]])

In [56]:
# Given the X python list convert it to an Y numpy array

x = [1 , 2 , 3]
x

x_array = np.array(x)
x_array

print(f"List = {x} and Datatype = {type(x)}" )
print(f"Array = {x_array} and Datatype = {type(x_array)}")

List = [1, 2, 3] and Datatype = <class 'list'>
Array = [1 2 3] and Datatype = <class 'numpy.ndarray'>


In [58]:
# Given the X numpy array, make a copy and store it on Y.

new_x_array = np.array(4)

y = np.copy(new_x_array)

print(f"Array_x = {new_x_array} \nY = {y}")

Array_x = 4 
Y = 4


In [61]:
# Create a numpy array with numbers from 1 to 10

random_ten = np.arange(1 ,11)
random_ten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
# Create a numpy array with the odd numbers between 1 to 10

random_odd = np.arange( 1 , 11 , step= 2)
random_odd

array([1, 3, 5, 7, 9])

In [67]:
# Create a numpy array with numbers from 1 to 10, in descending order.

descending_array = np.arange(1 , 11 )[:: -1]
descending_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [91]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

three_matrix = np.array([[0 , 1 , 2] , [3 ,4 ,5] , [6 ,7 ,8]])
three_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

method_2_matrix = np.arange( 0 , 9).reshape(3 , 3)
method_2_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])