In [1]:
# Some of the mathematical opeartions you can perform in an array
# eg sum , meam , mode , (measures of centray rendency and dispersion)

In [2]:
import numpy as np


In [3]:
single_array = np.array([1 ,2,3,4,5,6,7])
single_array

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# We perform some of the operations of central tendency

single_array.sum()

np.int64(28)

In [ ]:
# maximun number in the array

single_array.max()

np.int64(7)

In [ ]:
# standard deviation

single_array.std()

# variance

single_array.var()

# And many more

In [11]:
# We try and perform mathematical operations on matrices(multi-dimensional array)


multi_array = np.array([
    [1 , 2, 3] ,
    [4 ,5 ,6] ,
    [7 ,8 , 9]
])
multi_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Sum or size of that multidimensional array

multi_array.sum()

np.int64(45)

In [13]:
# mean , standard deviation , variance

multi_array.mean()

multi_array.std()

multi_array.var()

np.float64(6.666666666666667)

In [ ]:
# we can do a mathematical operation of each column

# performs a sum of each column (column1 , column2 , column3)

# axis 0 means columns

multi_array.sum(axis= 0)

array([12, 15, 18])

In [17]:
# axis 1 means rows

multi_array.sum(axis= 1)

array([ 6, 15, 24])